# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-eks-karpenter-controller
  description: "This component provisions Karpenter on an EKS cluster. It requires at least version 0.32.0 of Karpenter, though you are encouraged to use the latest version"
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component
